config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations"}
  resources :games
  resources :played_games
  scope "games/:game_id" do
    resources :game_steps
  end
  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base

	belongs_to :host, class_name: 'User'
	has_many :played_games
	has_many :users, :through => :played_games

	validates :number_of_players, :presence => true
	validate :must_have_enough_races, :if => :active_or_races?
	validate :must_have_eight_strategy_cards, :if => :active_or_strategy_cards?
	validate :must_have_objectives, :if => :active_or_strategy_cards?
	validate :must_select_trade_iii, :if => :playing_with_mercs?
	validate :must_select_assembly_ii, :if => :playing_with_political_intrigue?

	def select_races
		races = ["The Emirates of Hacan","The Universities of Jol-Nar","The Barony of Letnev","The Sardakk N'orr","The Federation of Sol","The Xxcha Kingdom","The L1Z1X Mindnet","The Mentak Coalition","The Naalu Colletive","The Yssaril Tribes"]
		if self.shattered_empire == true then races.push("The Embers of Muatt","The Clan of Saar","The Winnu","The Yin Brotherhood") end
		if self.shards_of_the_throne == true then races.push("The Arborec","The Ghosts of Creuss","The Nekro Virus") end
		return races
	end

	def select_rules
		rules = ["The Long War","Age Of Empire","Distant Suns","Leaders","Sabotage Runs"]
		if self.shattered_empire == true then rules.push("Race-Specific Technologies","Artifacts","Shock Troops","Space Mines","The Wormhole Nexus","Facilities","Tactical Retreats","Territorial Distant-Suns","Custodians of Mecatol Rex","Voice of the Council","Simulated Early Turns") end
		if self.shards_of_the_throne == true then rules.push("Preliminary Objectives","Flagships","The Final Frontier","Mechanized Units","Mercenaries","Political Intrigue") end
		return rules
	end

	def select_strategy_cards
		strategy_cards = {"Initiative" => 1, "Diplomacy" => 2, "Political" => 3, "Logistics" => 4, "Trade" => 5, "Warfare" => 6, "Technology" => 7,"Imperial" => 8}
		if self.shattered_empire == true then strategy_cards.merge!("Leadership" => 1,"Diplomacy II" => 2,"Assembly" => 3,"Production" => 4,"Trade II" => 5,"Warfare II" => 6,"Technology II" => 7,"Bureaucracy" => 8,"Imperial II" =>8) end
		if self.shards_of_the_throne == true then strategy_cards.merge!("Trade III" => 5,"Political II" => 3,"Assembly II" => 3) end
		return strategy_cards
	end

	def active?
  		status == 'active'
	end

 	def active_or_races?
		status.include? "races" || active?
	end

	def active_or_rules?
		status.include? "rules" || active?
	end

	def active_or_strategy_cards?
		status.include? "strategy" || active?
	end

	def must_have_enough_races
		errors.add(:races, "must have enough races for all players") if 
			eval(races).length < number_of_players		
	end

	def must_have_eight_strategy_cards
		errors.add(:strategy_cards, "must have eight strategy cards") if 
			eval(strategy_cards).length != 8	
	end		

	def must_have_objectives
	## Must choose a strat which allows objectives to get out unless has selected Age of Empirere
    ## Means imperial, bureaucracy
    	errors.add(:strategy_cards, "you must select a strategy card which allows you to get objectives onto the table (Imperial or Bureaucracy) unless playing with Age of Empire optional rule.") unless
  			strategy_cards.include?("Imperial") || strategy_cards.include?("Bureaucracy") || rules.include?("Age of Empire")  		
	end

	def playing_with_mercs?
		 ( status.include? "strategy" || active? ) && rules.include?("Mercenaries")
	end

	def must_select_trade_iii
    ## Must choose trade III if using Mercenaries
    	errors.add(:strategy_cards, "you must select Trade III if you are choosing to play with the Mercenaries optional rule.") unless
    	 	  strategy_cards.include?("Trade III")
    end

    def playing_with_political_intrigue?
		 ( status.include? "strategy" || active? ) && rules.include?("Political Intrigue")
    end

    def must_select_assembly_ii
    ## Must choose Assembly II if using Political Intrigue
    	errors.add(:strategy_cards, "you must select Assembly II if you are choosing to play with the Political Intrigue optional rule.") unless
    	 	  strategy_cards.include?("Assembly II")    
    end 	

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = current_user.hosted_games.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.hosted_games.new(game_params)
    @game.status = "status"
    respond_to do |format|
      if @game.save
        format.html { redirect_to game_steps_path(:game_id => @game.id), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:status,:shattered_empire, :shards_of_the_throne, :number_of_players, :races, :rules, :strategy_cards, :players)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shattered_empire %><br>
    <%= f.check_box :shattered_empire %>
  </div>
  <div class="field">
    <%= f.label :shards_of_the_throne %><br>
    <%= f.check_box :shards_of_the_throne %>
  </div>
  <div class="field">
    <%= f.label :number_of_players %><br>
    <%= f.number_field :number_of_players, in: 2..8, step: 1 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_notfullgame.html.erb
<p>
  <strong>Shattered empire:</strong>
  <%= @game.shattered_empire %>
</p>

<p>
  <strong>Shards of the throne:</strong>
  <%= @game.shards_of_the_throne %>
</p>

<p>
  <strong>Number of players:</strong>
  <%= @game.number_of_players %>
</p>

<p>
  <strong>Races:</strong>
  <%= @game.races %>
</p>

<p>
  <strong>Rules:</strong>
  <%= @game.rules %>
</p>

<p>
  <strong>Strategy cards:</strong>
  <%= @game.strategy_cards %>
</p>

<p>
  <strong>Address:</strong>
  <%= @game.address %>
</p>

<p>
  <strong>Time:</strong>
  <%= @game.date_and_time %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @game.notes %>
</p>

<table>
  <thead>
    <tr>
      <th>Invited Users</th>
      <th>Confirmed (RSVP'd) Users</th>
      <th>Spots Left : <%= @game.number_of_players - @game.played_games.length %></th>

    </tr>
  </thead>

  <tbody>
    <% @game.played_games.each do |game| %>
      <tr>
        <% if game.rsvp == false %>
          <td><%= game.user.email %></td>
          <td></td>
        <% else %>
         <td></td>
         <td><%= game.user.id %></td>
        <% end %>
        <td><%= link_to 'Delete Invitation', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/_showhost.html.erb
<table>
  <thead>
    <tr>
      <th>Shattered empire</th>
      <th>Shards of the throne</th>
      <th>Number of players</th>
      <th>Races</th>
      <th>Rules</th>
      <th>Strategy cards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.hosted_games.each do |game| %>
      <tr>
        <td><%= game.shattered_empire %></td>
        <td><%= game.shards_of_the_throne %></td>
        <td><%= game.number_of_players %></td>
        <td><%= game.races %></td>
        <td><%= game.rules %></td>
        <td><%= game.strategy_cards %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Cancel Game', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if game.number_of_players - 1 > game.played_games.length %>
          <td><%= link_to 'Invite User', new_played_game_path(:game_id => game.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/_showinvited.html.erb
<table>
  <thead>
    <tr>
      <th>Shattered empire</th>
      <th>Shards of the throne</th>
      <th>Number of players</th>
      <th>Races</th>
      <th>Rules</th>
      <th>Strategy cards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.played_games.each do |played_game| %>
      <% if played_game.rsvp == false  %>
        <tr>
          <td><%= played_game.game.shattered_empire %></td>
          <td><%= played_game.game.shards_of_the_throne %></td>
          <td><%= played_game.game.number_of_players %></td>
          <td><%= played_game.game.races %></td>
          <td><%= played_game.game.rules %></td>
          <td><%= played_game.game.strategy_cards %></td>
          <td><%= link_to 'Show', played_game.game %></td>
          <td><%= link_to 'RSVP', edit_played_game_path(played_game) %></td>
        </tr>
      <% end %>  
    <% end %>
  </tbody>
</table>

app/views/games/_showrsvp.html.erb
<table>
  <thead>
    <tr>
      <th>Shattered empire</th>
      <th>Shards of the throne</th>
      <th>Number of players</th>
      <th>Races</th>
      <th>Rules</th>
      <th>Strategy cards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.played_games.all.each do |played_game| %>
      <% if played_game.rsvp == true  %>
        <tr>
          <td><%= played_game.game.shattered_empire %></td>
          <td><%= played_game.game.shards_of_the_throne %></td>
          <td><%= played_game.game.number_of_players %></td>
          <td><%= played_game.game.races %></td>
          <td><%= played_game.game.rules %></td>
          <td><%= played_game.game.strategy_cards %></td>
          <td><%= link_to 'Show', played_game.game %></td>
          <td> <%= link_to 'Cancel', played_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>  
    <% end %>
  </tbody>
</table>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing Games</h1>



<h2>Games That You Are Hosting</h2>
<%= render 'showhost' %>
<br>
<h2>Upcoming Games</h2>
<%= render 'showrsvp' %>
<br>
<h2>Games That You Have Been Invited To</h2>
<%= render 'showinvited' %>
<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>Select Expansions and Number of Players</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<%= render 'notfullgame' %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>